// =============================================================
// IKA Fashion — In-memory data store (runtime).
// Dữ liệu sản phẩm seed sẵn; users/carts/orders/wishlist rỗng
// lúc khởi động và được điền qua API. Tham khảo database/migration.sql
// để triển khai PostgreSQL thật.
// =============================================================

const T_SIZES = ['S', 'M', 'L', 'XL', 'XXL'];
const P_SIZES = ['28', '30', '32', '34', '36', '38'];
const SHIRT_FEAT = ['Vải Premium', 'Nhanh Khô', 'Thoáng Khí', 'Không Phai'];
const POLO_FEAT  = ['Vải Piqué', 'Kháng Nhăn', 'Khí Chất', 'Bền Lâu'];
const QUAN_FEAT  = ['Slim Fit', 'Co Giãn', 'Tôn Dáng', 'Bền Lâu'];

export const products = new Map([
  // ── Sản phẩm thường ──────────────────────────────────────────────────────
  [1,  { id: 1,  name: 'Áo Thun Trắng Premium', handle: 'ao-thun-trang', collection: 'ao-thun', type: 'Áo Thun', price: 299000, img: '/products/ao-thun-trang.png', images: ['/products/ao-thun-trang.png'], colors: ['Trắng'],     sizes: T_SIZES, features: SHIRT_FEAT, rating: 4.8, sold: 152, stock: 120, description: 'Áo thun trắng tinh khôi, vải 100% cotton, thoáng khí, nhanh khô với công nghệ AirDry™' }],
  [2,  { id: 2,  name: 'Áo Thun Đen Premium',   handle: 'ao-thun-den',   collection: 'ao-thun', type: 'Áo Thun', price: 299000, img: '/products/ao-thun-den.png',   images: ['/products/ao-thun-den.png'],   colors: ['Đen'],       sizes: T_SIZES, features: SHIRT_FEAT, rating: 4.9, sold: 203, stock: 100, description: 'Áo thun đen đẹp, vải 100% cotton, thoáng khí, nhanh khô với công nghệ AirDry™' }],
  [3,  { id: 3,  name: 'Áo Thun Xanh Navy',     handle: 'ao-thun-xanh',  collection: 'ao-thun', type: 'Áo Thun', price: 299000, img: '/products/ao-thun-xanh.png',  images: ['/products/ao-thun-xanh.png'],  colors: ['Xanh Navy'], sizes: T_SIZES, features: SHIRT_FEAT, rating: 4.7, sold: 98,  stock: 80,  description: 'Áo thun xanh navy lịch sự, vải 100% cotton, thoáng khí, nhanh khô' }],
  [4,  { id: 4,  name: 'Áo Thun Xám',           handle: 'ao-thun-xam',   collection: 'ao-thun', type: 'Áo Thun', price: 299000, img: '/products/ao-thun-xam.png',   images: ['/products/ao-thun-xam.png'],   colors: ['Xám'],       sizes: T_SIZES, features: SHIRT_FEAT, rating: 4.6, sold: 74,  stock: 90,  description: 'Áo thun xám trung tính, vải 100% cotton, thoáng khí, nhanh khô' }],

  [5,  { id: 5,  name: 'Áo Polo Trắng',     handle: 'ao-polo-trang', collection: 'ao-polo', type: 'Áo Polo', price: 399000, img: '/products/ao-polo-white.png', images: ['/products/ao-polo-white.png'], colors: ['Trắng'],     sizes: T_SIZES, features: POLO_FEAT, rating: 4.8, sold: 110, stock: 70, description: 'Áo polo trắng sang trọng, vải piqué cao cấp, phù hợp mặc đi làm' }],
  [6,  { id: 6,  name: 'Áo Polo Xanh Navy', handle: 'ao-polo-xanh',  collection: 'ao-polo', type: 'Áo Polo', price: 399000, img: '/products/ao-polo-blue.png',  images: ['/products/ao-polo-blue.png'],  colors: ['Xanh Navy'], sizes: T_SIZES, features: POLO_FEAT, rating: 4.7, sold: 87,  stock: 65, description: 'Áo polo xanh navy lịch sự, vải piqué cao cấp, phù hợp mặc đi làm' }],
  [7,  { id: 7,  name: 'Áo Polo Đỏ',        handle: 'ao-polo-do',    collection: 'ao-polo', type: 'Áo Polo', price: 399000, img: '/products/ao-polo-red.png',   images: ['/products/ao-polo-red.png'],   colors: ['Đỏ'],        sizes: T_SIZES, features: POLO_FEAT, rating: 4.6, sold: 63,  stock: 55, description: 'Áo polo đỏ nổi bật, vải piqué cao cấp, phù hợp mặc dạo phố' }],
  [8,  { id: 8,  name: 'Áo Polo Đen',       handle: 'ao-polo-den',   collection: 'ao-polo', type: 'Áo Polo', price: 399000, img: '/products/ao-polo-black.png', images: ['/products/ao-polo-black.png'], colors: ['Đen'],       sizes: T_SIZES, features: POLO_FEAT, rating: 4.9, sold: 134, stock: 60, description: 'Áo polo đen thanh lịch, vải piqué cao cấp, phù hợp mặc đi làm' }],

  [9,  { id: 9,  name: 'Quần Đen Slim Fit',   handle: 'quan-den',  collection: 'quan', type: 'Quần', price: 499000, img: '/products/quan-den.png',  images: ['/products/quan-den.png'],  colors: ['Đen'],       sizes: P_SIZES, features: QUAN_FEAT, rating: 4.8, sold: 91, stock: 50, description: 'Quần đen slim fit hiện đại, tôn dáng, công nghệ co giãn FlexFit™' }],
  [10, { id: 10, name: 'Quần Jean Xanh Navy', handle: 'quan-xanh', collection: 'quan', type: 'Quần', price: 599000, img: '/products/quan-xanh.png', images: ['/products/quan-xanh.png'], colors: ['Xanh Navy'], sizes: P_SIZES, features: ['Jean Premium', 'Co Giãn', 'Thoải Mái', 'Bền Lâu'], rating: 4.7, sold: 68, stock: 45, description: 'Quần jean xanh navy chất lượng cao, co giãn thoải mái' }],
  [11, { id: 11, name: 'Quần Kaki Casual',    handle: 'quan-kaki', collection: 'quan', type: 'Quần', price: 449000, img: '/products/quan-kaki.png', images: ['/products/quan-kaki.png'], colors: ['Kaki'],      sizes: P_SIZES, features: ['Casual', 'Thoải Mái', 'Dễ Chăm Sóc', 'Bền Lâu'], rating: 4.6, sold: 57, stock: 60, description: 'Quần kaki casual thoải mái, phù hợp mặc hàng ngày' }],
  [12, { id: 12, name: 'Quần Xám Formal',     handle: 'quan-xam',  collection: 'quan', type: 'Quần', price: 549000, img: '/products/quan-xam.png',  images: ['/products/quan-xam.png'],  colors: ['Xám'],       sizes: P_SIZES, features: ['Formal', 'Sang Trọng', 'Chất Vải Tốt', 'Bền Lâu'], rating: 4.7, sold: 44, stock: 40, description: 'Quần xám formal sang trọng, phù hợp mặc đi làm và dự tiệc' }],

  // ── Sản phẩm Áo Polo giảm giá ────────────────────────────────────────────
  [13, { id: 13, name: 'Áo Polo Bo Sọc Form Regular PO136 Màu Trắng',  handle: 'sale-polo-1', collection: 'sale', type: 'Áo Polo', price: 270000, img: '/Giam-Gia/Ao/Ao-Polo/Polo-1.jpg',  images: ['/Giam-Gia/Ao/Ao-Polo/Polo-1.jpg'],  colors: ['Trắng', 'Đen'], sizes: T_SIZES, features: [...POLO_FEAT, 'Giảm 40%'], rating: 4.8, sold: 312, stock: 80, description: 'Áo polo bo sọc form regular, vải piqué cao cấp thoáng mát, kháng nhăn xuất sắc — đang giảm 40%.' }],
  [14, { id: 14, name: 'Áo Thun Lạnh Thể Thao Thoáng Mát Navy BS3234', handle: 'sale-polo-2', collection: 'sale', type: 'Áo Polo', price: 429000, img: '/Giam-Gia/Ao/Ao-Polo/Polo-2.jpg',  images: ['/Giam-Gia/Ao/Ao-Polo/Polo-2.jpg'],  colors: ['Đen', 'Navy'],  sizes: T_SIZES, features: [...POLO_FEAT, 'Giảm 34%'], rating: 4.9, sold: 189, stock: 65, description: 'Áo thun lạnh thể thao BS3234, công nghệ làm mát AirCool™ giữ thoáng mát suốt ngày — giảm 34%.' }],
  [15, { id: 15, name: 'Áo Polo Màu Trơn Nam Ngắn Tay',               handle: 'sale-polo-3', collection: 'sale', type: 'Áo Polo', price: 354000, img: '/Giam-Gia/Ao/Ao-Polo/Polo-3.jpg',  images: ['/Giam-Gia/Ao/Ao-Polo/Polo-3.jpg'],  colors: ['Xanh', 'Trắng', 'Đen'], sizes: T_SIZES, features: [...POLO_FEAT, 'Giảm 40%'], rating: 4.7, sold: 254, stock: 90, description: 'Áo polo màu trơn ngắn tay nam, vải piqué mềm mịn kháng nhăn — đang giảm 40%.' }],
  [16, { id: 16, name: 'Áo Polo Nam Màu Xanh Lá - North Sails',       handle: 'sale-polo-4', collection: 'sale', type: 'Áo Polo', price: 168000, img: '/Giam-Gia/Ao/Ao-Polo/Polo-4.webp', images: ['/Giam-Gia/Ao/Ao-Polo/Polo-4.webp'], colors: ['Xanh Lá'],      sizes: T_SIZES, features: [...POLO_FEAT, 'Giảm 40%'], rating: 4.6, sold: 421, stock: 55, description: 'Áo polo North Sails màu xanh lá tươi, chất vải cotton piqué thấm hút mồ hôi — giảm 40%.' }],
  [17, { id: 17, name: 'Áo Polo Nam Regular Fit Màu Trắng',           handle: 'sale-polo-5', collection: 'sale', type: 'Áo Polo', price: 499000, img: '/Giam-Gia/Ao/Ao-Polo/Polo-5.webp', images: ['/Giam-Gia/Ao/Ao-Polo/Polo-5.webp'], colors: ['Trắng'],        sizes: T_SIZES, features: [...POLO_FEAT, 'Giảm 36%'], rating: 4.8, sold: 143, stock: 70, description: 'Áo polo regular fit màu trắng tinh tế, vải cao cấp không nhàu — đang giảm 36%.' }],
  [18, { id: 18, name: 'Áo Polo Saint Laurent',                       handle: 'sale-polo-6', collection: 'sale', type: 'Áo Polo', price: 234000, img: '/Giam-Gia/Ao/Ao-Polo/Polo-6.webp', images: ['/Giam-Gia/Ao/Ao-Polo/Polo-6.webp'], colors: ['Trắng', 'Đen'], sizes: T_SIZES, features: [...POLO_FEAT, 'Giảm 40%'], rating: 4.5, sold: 367, stock: 45, description: 'Áo polo Saint Laurent thiết kế thanh lịch, chất liệu piqué cao cấp — đang giảm 40%.' }],
  [19, { id: 19, name: 'Áo Polo Ralph Lauren',                        handle: 'sale-polo-7', collection: 'sale', type: 'Áo Polo', price: 312000, img: '/Giam-Gia/Ao/Ao-Polo/Polo-7.webp', images: ['/Giam-Gia/Ao/Ao-Polo/Polo-7.webp'], colors: ['Nhiều màu'],    sizes: T_SIZES, features: [...POLO_FEAT, 'Giảm 40%'], rating: 4.9, sold: 98,  stock: 60, description: 'Áo polo Ralph Lauren đẳng cấp, biểu tượng thời trang phổ biến toàn cầu — đang giảm 40%.' }],
  [20, { id: 20, name: 'Áo Polo Unisex Cổ Bẻ Tay Ngắn',             handle: 'sale-polo-8', collection: 'sale', type: 'Áo Polo', price: 609000, img: '/Giam-Gia/Ao/Ao-Polo/Polo-8.webp', images: ['/Giam-Gia/Ao/Ao-Polo/Polo-8.webp'], colors: ['Trắng', 'Đen', 'Xanh'], sizes: T_SIZES, features: [...POLO_FEAT, 'Giảm 30%'], rating: 4.7, sold: 211, stock: 75, description: 'Áo polo unisex cổ bẻ tay ngắn, form dáng unisex phù hợp mọi vóc dáng — đang giảm 30%.' }],

  // ── Sản phẩm Áo Thun giảm giá ────────────────────────────────────────────
  [21, { id: 21, name: 'Áo Thun Trắng Premium Classic',               handle: 'sale-thun-1', collection: 'sale', type: 'Áo Thun', price: 270000, img: '/Giam-Gia/Ao/Ao-SoMi/SoMi-1.jpg', images: ['/Giam-Gia/Ao/Ao-SoMi/SoMi-1.jpg'], colors: ['Trắng'],        sizes: T_SIZES, features: [...SHIRT_FEAT, 'Giảm 40%'], rating: 4.8, sold: 312, stock: 100, description: 'Áo thun trắng Premium Classic, 100% cotton combed mềm mịn, thoáng khí — đang giảm 40%.' }],
  [22, { id: 22, name: 'Áo Thun Kẻ Sọc Premium',                     handle: 'sale-thun-2', collection: 'sale', type: 'Áo Thun', price: 364000, img: '/Giam-Gia/Ao/Ao-SoMi/SoMi-2.jpg', images: ['/Giam-Gia/Ao/Ao-SoMi/SoMi-2.jpg'], colors: ['Trắng Sọc'],    sizes: T_SIZES, features: [...SHIRT_FEAT, 'Giảm 30%'], rating: 4.9, sold: 189, stock: 80,  description: 'Áo thun kẻ sọc Premium, thiết kế classic không bao giờ lỗi mốt — đang giảm 30%.' }],
  [23, { id: 23, name: 'Áo Thun Nam Slim Fit Xanh Navy',              handle: 'sale-thun-3', collection: 'sale', type: 'Áo Thun', price: 354000, img: '/Giam-Gia/Ao/Ao-SoMi/SoMi-3.jpg', images: ['/Giam-Gia/Ao/Ao-SoMi/SoMi-3.jpg'], colors: ['Xanh Navy'],    sizes: T_SIZES, features: [...SHIRT_FEAT, 'Giảm 40%'], rating: 4.7, sold: 254, stock: 90,  description: 'Áo thun slim fit xanh navy tôn dáng, vải cotton co giãn nhẹ — đang giảm 40%.' }],
  [24, { id: 24, name: 'Áo Thun Xám EasyCare',                       handle: 'sale-thun-4', collection: 'sale', type: 'Áo Thun', price: 288000, img: '/Giam-Gia/Ao/Ao-SoMi/SoMi-4.jpg', images: ['/Giam-Gia/Ao/Ao-SoMi/SoMi-4.jpg'], colors: ['Xám'],          sizes: T_SIZES, features: [...SHIRT_FEAT, 'Giảm 40%'], rating: 4.6, sold: 421, stock: 110, description: 'Áo thun xám EasyCare kháng nhăn, dễ chăm sóc, mặc đi làm đi chơi đều đẹp — đang giảm 40%.' }],
  [25, { id: 25, name: 'Áo Thun Nam AirLight Trắng',                  handle: 'sale-thun-5', collection: 'sale', type: 'Áo Thun', price: 330000, img: '/Giam-Gia/Ao/Ao-SoMi/SoMi-5.jpg', images: ['/Giam-Gia/Ao/Ao-SoMi/SoMi-5.jpg'], colors: ['Trắng'],        sizes: T_SIZES, features: [...SHIRT_FEAT, 'Giảm 40%'], rating: 4.8, sold: 143, stock: 75,  description: 'Áo thun AirLight siêu nhẹ, thoáng mát ngay cả những ngày nóng bức — đang giảm 40%.' }],
  [26, { id: 26, name: 'Áo Thun Đen Dài Tay FormFit',                handle: 'sale-thun-6', collection: 'sale', type: 'Áo Thun', price: 372000, img: '/Giam-Gia/Ao/Ao-SoMi/SoMi-6.jpg', images: ['/Giam-Gia/Ao/Ao-SoMi/SoMi-6.jpg'], colors: ['Đen'],          sizes: T_SIZES, features: [...SHIRT_FEAT, 'Giảm 40%'], rating: 4.5, sold: 367, stock: 60,  description: 'Áo thun đen dài tay FormFit ôm dáng, vải cotton mỏng nhẹ mặc rất thoải mái — đang giảm 40%.' }],
  [27, { id: 27, name: 'Áo Thun Classic Fit Màu Đen - Calvin Klein',  handle: 'sale-thun-7', collection: 'sale', type: 'Áo Thun', price: 468000, img: '/Giam-Gia/Ao/Ao-SoMi/SoMi-7.webp',images: ['/Giam-Gia/Ao/Ao-SoMi/SoMi-7.webp'],colors: ['Đen'],          sizes: T_SIZES, features: [...SHIRT_FEAT, 'Giảm 40%'], rating: 4.9, sold: 98,  stock: 50,  description: 'Áo thun Calvin Klein classic fit màu đen huyền thoại, chất vải cao cấp bền đẹp — đang giảm 40%.' }],
  [28, { id: 28, name: 'Áo Thun Unisex Basic',                        handle: 'sale-thun-8', collection: 'sale', type: 'Áo Thun', price: 294000, img: '/Giam-Gia/Ao/Ao-SoMi/SoMi-8.jpg', images: ['/Giam-Gia/Ao/Ao-SoMi/SoMi-8.jpg'], colors: ['Nhiều màu'],    sizes: T_SIZES, features: [...SHIRT_FEAT, 'Giảm 30%'], rating: 4.7, sold: 211, stock: 120, description: 'Áo thun unisex basic dành cho mọi người, dễ phối đồ với bất kỳ trang phục nào — đang giảm 30%.' }],

  // ── Sản phẩm Quần giảm giá ───────────────────────────────────────────────
  [29, { id: 29, name: 'Quần Trouser Trắng Trơn',                     handle: 'sale-quan-1', collection: 'sale', type: 'Quần', price: 312000, img: '/Giam-Gia/Quan/Quan-Tay/QuanTay-1.jpg',  images: ['/Giam-Gia/Quan/Quan-Tay/QuanTay-1.jpg'],  colors: ['Trắng'],      sizes: P_SIZES, features: [...QUAN_FEAT, 'Giảm 40%'], rating: 4.8, sold: 312, stock: 70,  description: 'Quần trouser trắng trơn thanh lịch, form suôn đứng tôn dáng — đang giảm 40%.' }],
  [30, { id: 30, name: 'Quần Âu Be Trơn',                             handle: 'sale-quan-2', collection: 'sale', type: 'Quần', price: 288000, img: '/Giam-Gia/Quan/Quan-Tay/QuanTay-2.jpg',  images: ['/Giam-Gia/Quan/Quan-Tay/QuanTay-2.jpg'],  colors: ['Be'],         sizes: P_SIZES, features: [...QUAN_FEAT, 'Giảm 40%'], rating: 4.7, sold: 205, stock: 65,  description: 'Quần âu be trơn công sở, vải cao cấp mặc thoải mái cả ngày dài — đang giảm 40%.' }],
  [31, { id: 31, name: 'Quần Tây Nam Thanh Lịch Tôn Dáng Form Slim',  handle: 'sale-quan-3', collection: 'sale', type: 'Quần', price: 330000, img: '/Giam-Gia/Quan/Quan-Tay/QuanTay-3.webp', images: ['/Giam-Gia/Quan/Quan-Tay/QuanTay-3.webp'], colors: ['Đen', 'Xám'],  sizes: P_SIZES, features: [...QUAN_FEAT, 'Giảm 40%'], rating: 4.6, sold: 178, stock: 55,  description: 'Quần tây slim fit thanh lịch tôn dáng, phù hợp văn phòng và sự kiện — đang giảm 40%.' }],
  [32, { id: 32, name: 'Quần Dài Công Sở Thẳng Nam Cao Cấp',         handle: 'sale-quan-4', collection: 'sale', type: 'Quần', price: 372000, img: '/Giam-Gia/Quan/Quan-Tay/QuanTay-4.webp', images: ['/Giam-Gia/Quan/Quan-Tay/QuanTay-4.webp'], colors: ['Đen', 'Navy'], sizes: P_SIZES, features: [...QUAN_FEAT, 'Giảm 40%'], rating: 4.9, sold: 143, stock: 40,  description: 'Quần dài công sở thẳng cao cấp, dáng đứng không nhàu, chuyên nghiệp — đang giảm 40%.' }],
  [33, { id: 33, name: 'Quần Jean Xanh Ôm Dáng Kiểu Anh',            handle: 'sale-quan-5', collection: 'sale', type: 'Quần', price: 408000, img: '/Giam-Gia/Quan/Quan-Tay/QuanTay-5.jpg',  images: ['/Giam-Gia/Quan/Quan-Tay/QuanTay-5.jpg'],  colors: ['Xanh Navy'],  sizes: P_SIZES, features: ['Jean Premium', 'Ôm Dáng', 'Thoải Mái', 'Giảm 40%'], rating: 4.8, sold: 312, stock: 60, description: 'Quần jean xanh ôm dáng kiểu Anh, cut chuẩn tôn dáng cả ngày — đang giảm 40%.' }],
  [34, { id: 34, name: 'Quần Tây Nam Xám Trơn Công Sở',              handle: 'sale-quan-6', collection: 'sale', type: 'Quần', price: 354000, img: '/Giam-Gia/Quan/Quan-Tay/QuanTay-6.jpg',  images: ['/Giam-Gia/Quan/Quan-Tay/QuanTay-6.jpg'],  colors: ['Xám'],        sizes: P_SIZES, features: [...QUAN_FEAT, 'Giảm 40%'], rating: 4.6, sold: 189, stock: 50,  description: 'Quần tây xám trơn công sở, vải chống nhăn cao cấp giữ phong độ suốt ngày — đang giảm 40%.' }],
  [35, { id: 35, name: 'Quần Kaki Nam Casual',                        handle: 'sale-quan-7', collection: 'sale', type: 'Quần', price: 450000, img: '/Giam-Gia/Quan/Quan-Tay/QuanTay-7.webp', images: ['/Giam-Gia/Quan/Quan-Tay/QuanTay-7.webp'], colors: ['Kaki', 'Be'],  sizes: P_SIZES, features: ['Casual', 'Thoải Mái', 'Dễ Chăm Sóc', 'Giảm 40%'], rating: 4.9, sold: 254, stock: 80, description: 'Quần kaki nam casual phong cách trẻ trung, phù hợp đi chơi cuối tuần — đang giảm 40%.' }],
  [36, { id: 36, name: 'Quần Âu Đen Trơn Slim Fit',                  handle: 'sale-quan-8', collection: 'sale', type: 'Quần', price: 384000, img: '/Giam-Gia/Quan/Quan-Tay/QuanTay-8.webp', images: ['/Giam-Gia/Quan/Quan-Tay/QuanTay-8.webp'], colors: ['Đen'],        sizes: P_SIZES, features: [...QUAN_FEAT, 'Giảm 40%'], rating: 4.7, sold: 421, stock: 45,  description: 'Quần âu đen slim fit thanh lịch, vải cao cấp kháng nhăn suốt ngày — đang giảm 40%.' }],
]);

export const collections = [
  { id: 1, slug: 'ao-thun', name: 'Áo Thun', img: '/products/ao-thun-trang.png' },
  { id: 2, slug: 'ao-polo', name: 'Áo Polo', img: '/products/ao-polo-white.png' },
  { id: 3, slug: 'quan',    name: 'Quần',    img: '/products/quan-den.png' },
  { id: 4, slug: 'sale',    name: 'Ưu Đãi', img: '/Giam-Gia/Ao/Ao-Polo/Polo-1.jpg' },
];


// Runtime stores (rỗng lúc khởi động, điền qua API)
export const users = new Map();         // id -> user
export const carts = new Map();         // userId -> { items: [{ productId, size, color, quantity }] }
export const orders = new Map();        // id -> order
export const wishlist = new Map();      // userId -> Set<productId>

// Messaging stores
export const conversations = new Map(); // conversationId -> { id, customerId, customerName, customerEmail, lastMessage, lastMessageAt, unreadByAdmin }
export const messages = new Map();      // messageId -> { id, conversationId, senderId, senderRole, senderName, content, createdAt, isRead }
